language: node_js

node_js:
- '0.10'
- '4'
- '6'
- '7'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

before_install:
  - export CXX=g++-5

install:
  - npm install

script:
  - true